### ISSUE TITLE
Issue1

### ISSUE THREAD

**Issue by vimonfort** [VicenteMonfort/reglasRamas#2]
Creación de Issue1 para discutir como lasmkls afdnjdfk njdks vnjsk lvnjdskl

**Comment by VicenteMonfort** [comment]
Deberías de ndskndsklad jfdkls fjdskl ñjfkldps.
Piensa ejekl jfeksl jfklds ñjfdls jfkdlsñ

**Comment by vimonfort** [comment]
De acuerdo.
Así lo haré......

**Comment by vimonfort** [comment]
ME pongo a ello
